Add RH-certified image and push to RH registry
This commit adds the following:
- Updates Dockerfile to build a RH image
- Adds a step in publish to push the RedHat registry
- Adds summon to the publish stage to inject the RedHat API key stored in Conjur at runtime

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -6,6 +6,7 @@ set -e
 
 readonly VERSION="$(short_version_tag)"
 readonly FULL_VERSION_TAG="$(full_version_tag)"
+readonly REDHAT_IMAGE="scan.connect.redhat.com/ospid-56594c20-22fc-4eeb-9c2e-402cf43bcb79/secrets-provider-for-k8s"
 
 readonly TAGS=(
   "$VERSION"
@@ -27,4 +28,19 @@ if [ "$GIT_DESCRIPTION" = "v${VERSION}" ]; then
     docker tag "$IMAGE_NAME:$FULL_VERSION_TAG" "$REGISTRY/$IMAGE_NAME:$tag"
     docker push "$REGISTRY/$IMAGE_NAME:$tag"
   done
+
+  # Publish only latest to Redhat Registries
+  echo "Tagging and pushing ${REDHAT_IMAGE}"
+  docker tag "secrets-provider-for-k8s-redhat:${FULL_VERSION_TAG}" "${REDHAT_IMAGE}:${VERSION}"
+
+  if docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"; then
+    # you can't push the same tag twice to redhat registry, so ignore errors
+    if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
+      echo 'RedHat push FAILED! (maybe the image was pushed already?)'
+      exit 0
+    fi
+  else
+    echo 'Failed to log in to scan.connect.redhat.com'
+    exit 1
+  fi
 fi
