Auto udpate

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -2,45 +2,108 @@
 
 set -e
 
+# The following is used to:
+# Publish images on pre-release and tag as edge
+# Promote pre-releases to releases and tag as latest
+
 . bin/build_utils
 
-readonly VERSION="$(short_version_tag)"
-readonly FULL_VERSION_TAG="$(full_version_tag)"
-readonly REDHAT_IMAGE="scan.connect.redhat.com/ospid-56594c20-22fc-4eeb-9c2e-402cf43bcb79/secrets-provider-for-k8s"
+function print_help() {
+  echo "Release Usage: $0"
+  echo "Promote Usage: $0 --source <VERSION> --target <VERSION>"
+  echo " --source <VERSION>: specify version number of local image"
+  echo " --target <VERSION>: specify version number of remote image"
+}
 
-readonly TAGS=(
-  "$VERSION"
-  "latest"
-)
+while [[ $# -gt 0 ]]; do
+  echo "in while loop"
+  case "$1" in
+  --source)
+    SOURCE_TAG="$2"
+    shift
+    ;;
+  --target)
+    REMOTE_TAG="$2"
+    shift
+    ;;
+  --help)
+    print_help
+    exit 1
+    ;;
+  *)
+    echo "Unknown option: $1"
+    print_help
+    exit 1
+    ;;
+  esac
+  shift
+done
+
+# Version derived from CHANGLEOG and automated release library
+VERSION=$(<VERSION)
+readonly VERSION
+FULL_VERSION_TAG="$VERSION-$(git_tag)"
+readonly FULL_VERSION_TAG
+readonly REDHAT_IMAGE="scan.connect.redhat.com/ospid-56594c20-22fc-4eeb-9c2e-402cf43bcb79/secrets-provider-for-k8s"
 
 readonly IMAGE_NAME="secrets-provider-for-k8s"
 
 readonly REGISTRY='cyberark'
 
-# if the tag matches the VERSION, push VERSION and latest releases
-# and x and x.y releases
-if [ "$GIT_DESCRIPTION" = "v${VERSION}" ]; then
-  echo "Revision $GIT_DESCRIPTION matches version $VERSION exactly. Pushing to Dockerhub..."
+# Defaults to edge release when no flags are specified.
+if [[ -z ${REMOTE_TAG:-} && -z ${SOURCE_TAG:-} ]]; then
+  echo "Performing edge release."
+  REMOTE_TAG=edge
+  SOURCE_TAG="$VERSION-$(git_tag)"
+  readonly TAGS=(
+    "$VERSION"
+    "$REMOTE_TAG"
+  )
 
-  for tag in "${TAGS[@]}" $(gen_versions "$VERSION"); do
+  for tag in "${TAGS[@]}"; do
     echo "Tagging and pushing $REGISTRY/$IMAGE_NAME:$tag"
+    #neil
+    echo "docker tag "$IMAGE_NAME:$SOURCE_TAG" "$REGISTRY/$IMAGE_NAME:$tag""
+    #neil
+    echo "docker push "$REGISTRY/$IMAGE_NAME:$tag""
+  done
+elif [[ -z ${REMOTE_TAG:-} || -z ${SOURCE_TAG:-} ]]; then
+  echo "Missing promotion flag(s)."
+  print_help
+  exit 1
 
-    docker tag "$IMAGE_NAME:$FULL_VERSION_TAG" "$REGISTRY/$IMAGE_NAME:$tag"
-    docker push "$REGISTRY/$IMAGE_NAME:$tag"
+elif [[ -v REMOTE_TAG && -v SOURCE_TAG ]]; then
+  # Promotes image based on flag values provided
+  echo "Promoting image to $REMOTE_TAG"
+  readonly TAGS=(
+    "$REMOTE_TAG"
+    "latest"
+  )
+
+  for tag in "${TAGS[@]}" $(gen_versions "$REMOTE_TAG"); do
+    echo "Tagging and pushing $REGISTRY/$IMAGE_NAME:$tag"
+    #neil
+    echo "docker tag "$IMAGE_NAME:$SOURCE_TAG" "$REGISTRY/$IMAGE_NAME:$tag""
+    #neil
+    echo "docker push "$REGISTRY/$IMAGE_NAME:$tag""
   done
 
   # Publish RedHat image to Internal Registry
-  docker tag "secrets-provider-for-k8s-redhat:${FULL_VERSION_TAG}" "$REGISTRY/secrets-provider-for-k8s-redhat:${VERSION}"
-  docker push "$REGISTRY/secrets-provider-for-k8s-redhat:${VERSION}"
+  #neil
+  echo "docker tag "secrets-provider-for-k8s-redhat:${FULL_VERSION_TAG}" "$REGISTRY/secrets-provider-for-k8s-redhat:${VERSION}""
+  #neil
+  echo "docker push "$REGISTRY/secrets-provider-for-k8s-redhat:${VERSION}""
 
   # Publish only latest to Redhat Registries
   echo "Tagging and pushing ${REDHAT_IMAGE}"
-  docker tag "secrets-provider-for-k8s-redhat:${FULL_VERSION_TAG}" "${REDHAT_IMAGE}:${VERSION}"
+  #neil
+  echo "docker tag "secrets-provider-for-k8s-redhat:${FULL_VERSION_TAG}" "${REDHAT_IMAGE}:${VERSION}""
 
   # Publish RedHat image to RedHat Registry
   if docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"; then
     # you can't push the same tag twice to redhat registry, so ignore errors
-    if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
+    #neil
+    if ! echo "docker push "${REDHAT_IMAGE}:${VERSION}""; then
       echo 'Red Hat push FAILED! (maybe the image was pushed already?)'
       exit 0
     fi
@@ -48,8 +111,9 @@ if [ "$GIT_DESCRIPTION" = "v${VERSION}" ]; then
     echo 'Failed to log in to scan.connect.redhat.com'
     exit 1
   fi
-elif [ "$BRANCH_NAME" = "main" ]; then
-  echo "Successful Master build. Tagging and pushing $REGISTRY/$IMAGE_NAME:edge"
-  docker tag "$IMAGE_NAME:$FULL_VERSION_TAG" "$REGISTRY/$IMAGE_NAME:edge"
-  docker push "$REGISTRY/$IMAGE_NAME:edge"
+
+else
+  echo "in else statement"
+  print_help
+  exit 1
 fi
