Update Redhat scanning registry to quay.io

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -60,17 +60,20 @@ while [[ $# -gt 0 ]]; do
   shift
 done
 
-readonly REDHAT_IMAGE="scan.connect.redhat.com/ospid-56594c20-22fc-4eeb-9c2e-402cf43bcb79/secrets-provider-for-k8s"
-readonly REDHAT_CERT_PID="5ec6353078e79e6a879fa296"
 readonly REDHAT_LOCAL_IMAGE="secrets-provider-for-k8s-redhat"
 readonly IMAGE_NAME="secrets-provider-for-k8s"
 readonly REGISTRY='cyberark'
 readonly LOCAL_REGISTRY='registry.tld'
+readonly REDHAT_REGISTRY="quay.io"
+readonly REDHAT_CERT_PID="5ec6353078e79e6a879fa296"
 # Version derived from CHANGLEOG and automated release library
 VERSION=$(<VERSION)
 readonly VERSION
 FULL_VERSION_TAG="$VERSION-$(git_tag)"
 readonly FULL_VERSION_TAG
+
+REDHAT_REMOTE_IMAGE="${REDHAT_REGISTRY}/redhat-isv-containers/${REDHAT_CERT_PID}"
+REDHAT_USER="redhat-isv-containers+${REDHAT_CERT_PID}-robot"
 
 if [[ ${PUBLISH_INTERNAL} = true ]]; then
   echo "Publishing built images internally to registry.tld."
@@ -121,21 +124,21 @@ if [[ ${PROMOTE} = true ]]; then
   tag_and_push "${LOCAL_REGISTRY}/${REDHAT_LOCAL_IMAGE}:${SOURCE_TAG}" "$REGISTRY/${REDHAT_LOCAL_IMAGE}:${REMOTE_TAG}"
 
   # Publish only latest to Redhat Registries
-  echo "Tagging and pushing ${REDHAT_IMAGE}"
-  docker tag "${LOCAL_REGISTRY}/${REDHAT_LOCAL_IMAGE}:${SOURCE_TAG}" "${REDHAT_IMAGE}:${REMOTE_TAG}"
+  echo "Tagging and pushing ${REDHAT_REMOTE_IMAGE}"
+  docker tag "${LOCAL_REGISTRY}/${REDHAT_LOCAL_IMAGE}:${SOURCE_TAG}" "${REDHAT_REMOTE_IMAGE}:${REMOTE_TAG}"
 
   # Publish RedHat image to RedHat Registry
-  if docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"; then
+  if docker login "${REDHAT_REGISTRY}" -u "${REDHAT_USER}" -p "${REDHAT_API_KEY}"; then
     # you can't push the same tag twice to redhat registry, so ignore errors
-    if ! docker push "${REDHAT_IMAGE}:${REMOTE_TAG}"; then
+    if ! docker push "${REDHAT_REMOTE_IMAGE}:${REMOTE_TAG}"; then
       echo 'Red Hat push FAILED! (maybe the image was pushed already?)'
       exit 0
     fi
 
     # scan image with preflight tool
-    scan_redhat_image "${REDHAT_IMAGE}:${REMOTE_TAG}" "${REDHAT_CERT_PID}"
+    scan_redhat_image "${REDHAT_REMOTE_IMAGE}:${REMOTE_TAG}" "${REDHAT_CERT_PID}"
   else
-    echo 'Failed to log in to scan.connect.redhat.com'
+    echo 'Failed to log in to quay.io'
     exit 1
   fi
 
